config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "top#index"
  get "top/index" 
  get "quiz/exam/:question_id" => "quiz#exam"
  get "quiz/result"
  post "judge", to: "quiz#judge"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :questions
  has_many :your_results
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :genre
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/user_result.rb
class UserResult < ApplicationRecord
    belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  def exam
    # ランダムに10問取り出す
    @question = Question.first
    # ↑デバッグ用
    
  end

  def judge
    @question = Question.first
    @select = params[:select].to_i

    if @question.correct_flag
      @flag = 1
    else
      @flag = 0
    end

    if @flag == @select
      puts "正解です"
      redirect_to quiz_result_path(params: {seigo: 1})
    else
      puts "不正解です"
      redirect_to quiz_result_path(params: {seigo: 0})
    end


  end
 
  def create_result
  end

  def result
    if params[:seigo].to_i == 1
      @result_flag = "正解です"
    else
      @result_flag = "不正解です"
    end

  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
        @genres = Genre.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quiz/exam.html.erb
<h1>回答ページ</h1>
<p><%= @question.content if @question.content %></p>

<input type="button" value="ヒント" onclick="clickBtn1()" />
<div id="hint">ヒント:<%= @question.hint if @question.hint %></div>

  <script>
    document.getElementById("hint").style.display ="none";
    function clickBtn1(){
      const hint = document.getElementById("hint");
      if(hint.style.display=="block"){
        hint.style.display ="none";
      }else{
        hint.style.display ="block";
      }
    }
  </script>

<%= button_to"○", judge_path(params: {select: 1}) %>
<%= button_to "x", judge_path(params: {select: 0}) %>

<%# ↑まるばつでcorrect_flagをパラメータで送る %>


<%= link_to "結果", quiz_result_path %>

app/views/quiz/result.html.erb
<h1>結果ページ</h1>
<h2>あなたの結果</h2>
<%= @result_flag %>

<%= link_to "Topに戻る", root_path %>

app/views/top/index.html.erb
<h1>Topページ</h1>
<% @genres.each do |genre| %>
  <%= link_to "#{genre.name}",controller: 'quiz',action:'exam',question_id: genre %>
<% end %>